<script lang="ts">
  import { s } from "$lib/client/localization.svelte";
  import { theme } from "$lib/stores/theme.svelte.js";
  import { onMount } from "svelte";

  // Props
  interface Props {
    showProgress?: boolean;
    progress?: number;
    stage?: string;
    hasError?: boolean;
    errorMessage?: string;
  }

  let {
    showProgress = false,
    progress = 0,
    stage = "",
    hasError = false,
    errorMessage = "",
  }: Props = $props();

  // Smooth animated progress counter
  let displayProgress = $state(0);
  let animationFrame: number;

  // Animation loop that runs continuously
  onMount(() => {
    const animate = () => {
      const diff = progress - displayProgress;

      // If we're close enough, just set it directly
      if (Math.abs(diff) < 0.1) {
        displayProgress = progress;
      } else {
        // Otherwise, animate towards the target
        // Use a smaller step for smoother animation
        displayProgress += diff * 0.08;
      }

      // Keep animating
      animationFrame = requestAnimationFrame(animate);
    };

    // Start animation
    animate();

    // Cleanup
    return () => {
      if (animationFrame) {
        cancelAnimationFrame(animationFrame);
      }
    };
  });
</script>

<div
  class="fixed inset-0 z-50 flex items-center justify-center bg-white dark:bg-dark-bg"
>
  <div class="text-center">
    <div class="relative mx-auto mb-4 h-40 w-40">
      <!-- Spin body (rotates clockwise) -->
      <img
        src="/svg/spin_body.svg"
        alt=""
        class="absolute inset-0 h-full w-full animate-spin-slow"
        class:brightness-75={hasError}
        class:sepia={hasError}
        class:hue-rotate-[320deg]={hasError}
        class:saturate-150={hasError}
      />

      <!-- Spin circle (rotates counter-clockwise) -->
      <img
        src={theme.current === "dark"
          ? "/svg/spin_circle_dark.svg"
          : "/svg/spin_circle_light.svg"}
        alt=""
        class="absolute inset-0 h-full w-full animate-spin-reverse"
        class:brightness-75={hasError}
        class:sepia={hasError}
        class:hue-rotate-[320deg]={hasError}
        class:saturate-150={hasError}
      />
    </div>
    <h1
      class="mb-2 flex items-center justify-center text-2xl font-bold text-gray-800 dark:text-dark-text"
    >
      <span>{s("app.title") || "Kite"}</span>
      <span
        class="mt-0.5 ml-2 rounded-lg bg-yellow-200 px-2 py-0.5 text-xs font-medium text-black"
      >
        {s("app.beta") || "BETA"}
      </span>
    </h1>
    <p class="text-xl text-gray-600 dark:text-gray-400">
      {s("app.motto") || "News. Elevated."}
    </p>

    {#if hasError}
      <div class="mt-4 text-center">
        <p class="text-red-500 dark:text-red-400 font-medium">
          {errorMessage || "An error occurred"}
        </p>
        <p class="text-sm text-gray-500 dark:text-gray-400 mt-1">
          {s("loading.errorFallback") ||
            "Continuing with limited functionality..."}
        </p>
      </div>
    {:else if showProgress}
      <div class="mt-4 text-center">
        <!-- Smooth percentage counter -->
        <p class="text-xl text-gray-600 dark:text-gray-400">
          {Math.round(displayProgress)}%
        </p>

        <!-- Loading stage -->
        <p class="min-h-[1.5rem] text-sm text-gray-500 dark:text-gray-400 mt-1">
          {stage || ""}
        </p>
      </div>
    {/if}

    <!-- Disclaimer about auto-generated content -->
    <div class="mt-6 text-center text-xs text-gray-500 dark:text-gray-400">
      <p>
        {s("app.disclaimerAutoGenerated") ||
          "Summaries are auto-generated and Kite can make mistakes."}
      </p>
      <p>
        {s("app.disclaimerVerify") || "Please verify important information."}
      </p>
    </div>
  </div>
</div>
